# -*- coding: utf-8 -*-
"""final_oct.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QpbdRHEgqAve4gHmO6FiRd3Xi14LI5nX
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle datasets download -d paultimothymooney/kermany2018

#!unzip /content/kermany2018.zip

import zipfile
zip_ref = zipfile.ZipFile('/content/kermany2018.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import tensorflow as tf
  from tensorflow import keras
  from keras import Sequential
  from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,BatchNormalization,Dropout

# generators
  train_ds = keras.utils.image_dataset_from_directory(
      directory = '/content/OCT2017 /train',
      labels='inferred',
      label_mode = 'int',
      batch_size=32,
      image_size=(256,256)
  )

  validation_ds = keras.utils.image_dataset_from_directory(
      directory = '/content/OCT2017 /test',
      labels='inferred',
      label_mode = 'int',
      batch_size=32,
      image_size=(256,256)
  )

# Normalize
def process(image,label):
    image = tf.cast(image/255. ,tf.float32)
    return image,label

train_ds = train_ds.map(process)
validation_ds = validation_ds.map(process)

def model():
# Defining model architecture
    model = Sequential()
    model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
    model.add(MaxPooling2D((2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2, 2)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2, 2)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2, 2)))
    model.add(Flatten())
    model.add(Dropout(0.5))
    model.add(Dense(4, activation='softmax'))

# Compiling model
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

model = model()
model.summary()

from keras.callbacks import ModelCheckpoint


path = "/content/drive/MyDrive/weights_improvement_mode1-{epoch:02d}-{val_accuracy: .2f}.hdf5"
model_checkpoint = tf.keras.callbacks.ModelCheckpoint(
    filepath= path,
    save_weights_only=True,
    monitor='val_accuracy',
    verbose=1,
    mode='max',
    save_best_only=True)


# Training the model
historyy = model.fit(train_ds,epochs=10, validation_data=validation_ds, callbacks=[model_checkpoint])

# load the weights from the best checkpoint
model.load_weights("/content/drive/MyDrive/weights_improvement_mode1-10-0.97.hdf5")

# evaluate the model on the test dataset
test_loss, test_acc = model.evaluate(validation_ds, verbose=2)
print('\nTest accuracy:', test_acc)

model.load_weights(path)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

model.save("oct.h5")

a=load_model(oct.h5)
validation_ds = keras.utils.image_dataset_from_directory(
      directory = '/content/OCT2017 /test',
      labels='inferred',
      label_mode = 'int',
      batch_size=32,
      image_size=(256,256)
  )

a.evaluate(valiation_ds)

import cv2 as cv
import tensorflow as tf
from tensorflow import keras
import numpy as np

a = "/content/OCT2017 /test/NORMAL/NORMAL-1025847-1.jpeg"
#a = "/content/OCT2017 /test/DME/DME-1274315-2.jpeg"
#a = "/content/OCT2017 /test/CNV/CNV-1016042-3.jpeg"
#a = "/content/OCT2017 /test/DRUSEN/DRUSEN-1225603-1.jpeg"
#a="C:\\Users\\aasma\\Downloads\\Backgrounds\\232094.jpg"

image=tf.io.read_file(a)
tensor=tf.io.decode_image(image,channels=3,dtype=tf.dtypes.float32)
tensor=tf.image.resize(tensor,[256,256])
input_tensor=tf.expand_dims(tensor,axis=0)

q = np.argmax(z.predict(input_tensor))
q

if q==0:
    print("cnv")
elif q==1:
    print("dme")
elif q==2:
    print("drusen")
elif q==3:
    print("normal")
else:
    print("Image is unidentifiable")